### PR TITLE
Remove link to GDPR assessment tool in gdpr-action-plan.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/Compliance/issues/41.

I understand that this tool is not available anymore for customers. They should contact an advisory partner.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder, please merge this PR. Thanks

**Comment by robmazz** [comment]
@yogkumgit - this was already taken care of in another PR.

**Pull request closed without merging**
